"""add broker_email to bids, cancelled bid status

Revision ID: 173786a3c066
Revises: a57817c3352a
Create Date: 2026-07-05 16:41:54.280670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '173786a3c066'
down_revision: Union[str, Sequence[str], None] = 'a57817c3352a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('broker_email', sa.String(length=255), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('draft', 'sent', 'recorded', 'accepted', 'rejected', 'failed', 'cancelled', name='bid_status'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('draft', 'sent', 'recorded', 'accepted', 'rejected', 'failed', 'cancelled', name='bid_status'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
        batch_op.drop_column('broker_email')

    # ### end Alembic commands ###