"""create loads, stops, bids

Revision ID: a62a042b7152
Revises: 
Create Date: 2026-07-05 14:17:46.884300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a62a042b7152'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loads',
    sa.Column('direction', sa.Enum('outbound', 'inbound', name='load_direction'), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('origin_city', sa.String(length=128), nullable=False),
    sa.Column('origin_state', sa.String(length=2), nullable=False),
    sa.Column('origin_lat', sa.Float(), nullable=False),
    sa.Column('origin_lng', sa.Float(), nullable=False),
    sa.Column('destination_city', sa.String(length=128), nullable=False),
    sa.Column('destination_state', sa.String(length=2), nullable=False),
    sa.Column('destination_lat', sa.Float(), nullable=False),
    sa.Column('destination_lng', sa.Float(), nullable=False),
    sa.Column('shipper_name', sa.String(length=255), nullable=False),
    sa.Column('distance_miles', sa.Integer(), nullable=False),
    sa.Column('weight_lbs', sa.Integer(), nullable=False),
    sa.Column('equipment_type', sa.String(length=64), nullable=False),
    sa.Column('posted_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pickup_deadhead_miles', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('broker_email', sa.String(length=255), nullable=False),
    sa.Column('broker_phone', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('available', 'bid_placed', 'booked', 'in_transit', 'delivered', name='load_status'), nullable=False),
    sa.Column('customer_company_name', sa.String(length=255), nullable=False),
    sa.Column('customer_contact_name', sa.String(length=255), nullable=True),
    sa.Column('customer_contact_phone', sa.String(length=32), nullable=True),
    sa.Column('driver_name', sa.String(length=255), nullable=True),
    sa.Column('driver_phone', sa.String(length=32), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loads_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_loads_order_id'), ['order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_loads_status'), ['status'], unique=False)

    op.create_table('bids',
    sa.Column('load_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.Enum('email', 'call', name='bid_method'), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'recorded', 'accepted', 'rejected', 'failed', name='bid_status'), nullable=False),
    sa.Column('rate_type', sa.Enum('all_in', 'per_mile', name='rate_type'), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('call_mode', sa.Enum('auto_agent', 'manual', name='call_mode'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bids_load_id'), ['load_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bids_status'), ['status'], unique=False)

    op.create_table('stops',
    sa.Column('load_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('stop_type', sa.Enum('pickup', 'delivery', name='stop_type'), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stops_load_id'), ['load_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stops_load_id'))

    op.drop_table('stops')
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bids_status'))
        batch_op.drop_index(batch_op.f('ix_bids_load_id'))

    op.drop_table('bids')
    with op.batch_alter_table('loads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loads_status'))
        batch_op.drop_index(batch_op.f('ix_loads_order_id'))
        batch_op.drop_index(batch_op.f('ix_loads_direction'))

    op.drop_table('loads')
    # ### end Alembic commands ###
