"""add bid_emails conversation history table

Revision ID: f2fed101f030
Revises: 173786a3c066
Create Date: 2026-07-05 17:01:38.374054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2fed101f030'
down_revision: Union[str, Sequence[str], None] = '173786a3c066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bid_emails',
    sa.Column('bid_id', sa.Uuid(), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('sent', 'recorded', 'failed', name='email_delivery_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bid_emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bid_emails_bid_id'), ['bid_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bid_emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bid_emails_bid_id'))

    op.drop_table('bid_emails')
    # ### end Alembic commands ###
